#!/usr/bin/env python3
"""Stage firmware sources for a board build.

Resolves the compiled file set (board-first for functions and config
headers), generates run_selection.h and fpga_opts.h, and syncs everything
into the staging directory with content-compare copies. The stamp file is
touched only when something actually changed, so make's rebuild tracking is
exact. Stdlib only.

Exit codes: 0 ok, 1 validation error.
"""

import argparse
import os
import re
import sys

OPT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=\S+$")
SRC_EXT = (".c", ".h", ".ld", ".S")


def fail(msg):
    print("stage.py: ERROR: %s" % msg, file=sys.stderr)
    sys.exit(1)


def list_names(directory):
    if not os.path.isdir(directory):
        return set()
    return {os.path.splitext(f)[0] for f in os.listdir(directory) if f.endswith(".c")}


def gather(repo, board, entry, entry_name, script, opts):
    """Return {staged_filename: content_bytes}."""
    files = {}

    def add_file(path, name=None):
        name = name or os.path.basename(path)
        if name in files:
            fail("duplicate staged file '%s' (from %s)" % (name, path))
        with open(path, "rb") as fh:
            files[name] = fh.read()

    common_src = os.path.join(repo, "common", "src")
    board_fw = os.path.join(repo, "boards", board, "fw")
    common_fn = os.path.join(repo, "common", "functions")
    board_fn = os.path.join(repo, "boards", board, "functions")
    common_cfg = os.path.join(repo, "common", "config")
    board_cfg = os.path.join(repo, "boards", board, "config")

    for d in (common_src, board_fw):
        if not os.path.isdir(d):
            fail("missing directory: %s" % d)
        for f in sorted(os.listdir(d)):
            if f.endswith(SRC_EXT):
                add_file(os.path.join(d, f))

    names = sorted(list_names(common_fn) | list_names(board_fn))
    if not names:
        fail("no functions found under common/functions or boards/%s/functions" % board)

    for n in names:
        board_impl = os.path.join(board_fn, n + ".c")
        common_impl = os.path.join(common_fn, n + ".c")
        add_file(board_impl if os.path.isfile(board_impl) else common_impl)

        cfg = "cfg_%s.h" % n
        board_c = os.path.join(board_cfg, cfg)
        common_c = os.path.join(common_cfg, cfg)
        if os.path.isfile(board_c):
            add_file(board_c)
        elif os.path.isfile(common_c):
            add_file(common_c)
        else:
            fail("function '%s' has no config header: provide common/config/%s "
                 "or boards/%s/config/%s" % (n, cfg, board, cfg))

    if script:
        if not os.path.isfile(script):
            fail("SCRIPT '%s' not found" % script)
        add_file(script, "user_script.c")

    opt_lines = ["/* generated by stage.py - OPTS= command-line overrides */"]
    for tok in opts.split():
        if not OPT_RE.match(tok):
            fail("bad OPTS token '%s' (expected NAME=value)" % tok)
        name, _, value = tok.partition("=")
        opt_lines.append("#define %s %s" % (name, value))
    files["fpga_opts.h"] = ("\n".join(opt_lines) + "\n").encode()

    sel = [
        "/* generated by stage.py - entry-point selection */",
        "#ifndef RUN_SELECTION_H",
        "#define RUN_SELECTION_H",
        "int %s(void);" % entry,
        "#define FPGA_ENTRY %s" % entry,
        '#define FPGA_ENTRY_NAME "%s"' % entry_name,
        "#endif",
    ]
    files["run_selection.h"] = ("\n".join(sel) + "\n").encode()

    return files


def sync(stage_dir, files):
    changed = False
    os.makedirs(stage_dir, exist_ok=True)

    for name in os.listdir(stage_dir):
        if name.endswith(SRC_EXT) and name not in files:
            os.remove(os.path.join(stage_dir, name))
            changed = True

    for name, content in files.items():
        dst = os.path.join(stage_dir, name)
        if os.path.isfile(dst):
            with open(dst, "rb") as fh:
                if fh.read() == content:
                    continue
        with open(dst, "wb") as fh:
            fh.write(content)
        changed = True

    return changed


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--repo", required=True)
    p.add_argument("--board", required=True)
    p.add_argument("--stage", required=True)
    p.add_argument("--stamp", required=True)
    p.add_argument("--entry", required=True)
    p.add_argument("--entry-name", required=True)
    p.add_argument("--script", default="")
    p.add_argument("--opts", default="")
    args = p.parse_args()

    files = gather(args.repo, args.board, args.entry, args.entry_name,
                   args.script, args.opts)
    changed = sync(args.stage, files)

    if changed or not os.path.isfile(args.stamp):
        with open(args.stamp, "w") as fh:
            fh.write("staged\n")
        print("stage.py: staged %d files (changed)" % len(files))
    else:
        print("stage.py: staged %d files (no changes)" % len(files))


if __name__ == "__main__":
    main()
